[workspace]
members = [
	"consensus",
	"message-broker",
	"network",
	"parachain-upgrade",
	"primitives",
	"rococo-parachains/",
	"rococo-parachains/pallets/parachain-info",
	"rococo-parachains/primitives",
	"rococo-parachains/runtime",
	"runtime",
	"service",
	"test/runtime",
	"test/client",
	"test/service",
	"test/relay-sproof-builder",
	"xcm-handler",
]

[profile.release]
panic = 'unwind'

[patch.crates-io]
trie-db = { git = 'https://github.com/cheme/trie', branch = 'skip_compact_values' }
hash-db = { git = 'https://github.com/cheme/trie', branch = 'skip_compact_values' }

[patch.'https://github.com/paritytech/substrate']
sp-core = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-client-api = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-treasury = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-randomness-collective-flip = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-babe = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-trie = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-keyring = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-timestamp = { git="https://github.com/cheme/substrate", branch="validation_io2" }
frame-system = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-staking = { git="https://github.com/cheme/substrate", branch="validation_io2" }
frame-support = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-session = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-balances = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-authorship = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-staking = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-runtime = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-io = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-std = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-inherents = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-api = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-sudo = { git="https://github.com/cheme/substrate", branch="validation_io2" }
frame-system-rpc-runtime-api = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-staking-reward-curve = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-offences = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-nicks = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-membership = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-indices = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-im-online = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-identity = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-grandpa = { git="https://github.com/cheme/substrate", branch="validation_io2" }
frame-executive = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-elections-phragmen = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-democracy = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-collective = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-transaction-payment-rpc = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-transaction-payment-rpc-runtime-api = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-transaction-payment = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-authority-discovery = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-transaction-pool = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-version = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-session = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-offchain = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-consensus-babe = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-recovery = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-society = { git="https://github.com/cheme/substrate", branch="validation_io2" }
fork-tree = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-utility = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-network = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-cli = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-client-db = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-executor = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-service = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-keystore = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-authority-discovery = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-block-builder = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-blockchain = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-network-gossip = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-state-machine = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-externalities = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-runtime-interface = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-application-crypto = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-serializer = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-rpc = { git="https://github.com/cheme/substrate", branch="validation_io2" }
substrate-frame-rpc-system = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-authority-discovery = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-chain-spec = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-finality-grandpa = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-telemetry = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-transaction-pool = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-timestamp = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-block-builder = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-finality-grandpa = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-tracing = { git="https://github.com/cheme/substrate", branch="validation_io2" }
substrate-prometheus-endpoint = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-keystore = { git="https://github.com/cheme/substrate", branch="validation_io2" }
frame-benchmarking = { git="https://github.com/cheme/substrate", branch="validation_io2" }
frame-benchmarking-cli = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-bounties = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-multisig = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-scheduler = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-tips = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-proxy = { git="https://github.com/cheme/substrate", branch="validation_io2" }
pallet-vesting = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-basic-authorship = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-consensus = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-consensus = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-consensus-babe = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-consensus-babe-rpc = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-consensus-epochs = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-consensus-slots = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-consensus-vrf = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-consensus-aura = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-wasm-interface = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-finality-grandpa-rpc = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-light = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-sync-state-rpc = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-arithmetic = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-storage = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sc-tracing = { git="https://github.com/cheme/substrate", branch="validation_io2" }
sp-test-primitives = { git="https://github.com/cheme/substrate", branch="validation_io2" }
substrate-build-script-utils = { git="https://github.com/cheme/substrate", branch="validation_io2" }
substrate-test-client = { git="https://github.com/cheme/substrate", branch="validation_io2" }
substrate-test-runtime = { git="https://github.com/cheme/substrate", branch="validation_io2" }
substrate-test-runtime-client = { git="https://github.com/cheme/substrate", branch="validation_io2" }
substrate-test-utils = { git="https://github.com/cheme/substrate", branch="validation_io2" }

[patch.'https://github.com/paritytech/polkadot']
#kusama-runtime = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
westend-runtime = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
rococo-runtime = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-runtime = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-runtime-common = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-runtime-parachains = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-cli = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-rpc = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-parachain = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-collator-protocol = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-primitives = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-core-primitives = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-node-primitives = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-node-subsystem = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-node-jaeger = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-node-collation-generation = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-statement-table = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-availability-distribution = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-availability-bitfield-distribution = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-overseer = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-service = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-erasure-coding = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-network-bridge = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-test-runtime = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-test-client = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-test-service = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-node-subsystem-test-helpers = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
polkadot-node-subsystem-util = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
xcm = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
xcm-builder = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
xcm-executor = { git="https://github.com/cheme/polkadot-1", branch="ext_wasm_old" }
