[workspace]
members = [
	"consensus",
	"message-broker",
	"network",
	"parachain-upgrade",
	"primitives",
	"rococo-parachains/",
	"rococo-parachains/contracts-runtime",
	"rococo-parachains/pallets/parachain-info",
	"rococo-parachains/primitives",
	"rococo-parachains/runtime",
	"runtime",
	"service",
	"test/runtime",
	"test/client",
	"xcm-handler",
]

[profile.release]
panic = 'unwind'
