[workspace]
members = [
	"client/cli",
	"client/consensus/common",
	"client/consensus/relay-chain",
	"client/network",
	"client/service",
	"pallets/parachain-system",
	"pallets/xcm-handler",
	"primitives/core",
	"primitives/parachain-inherent",
	"rococo-parachains/",
	"rococo-parachains/pallets/parachain-info",
	"rococo-parachains/primitives",
	"rococo-parachains/runtime",
	"test/runtime",
	"test/client",
	"test/service",
	"test/relay-sproof-builder",
]

[profile.release]
panic = "unwind"

[patch.'https://github.com/paritytech/substrate']
sp-core = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-maybe-compressed-blob = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-client-api = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-treasury = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-randomness-collective-flip = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-babe = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-trie = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-keyring = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-timestamp = { git="https://github.com/cheme/substrate", branch="validation_io" }
frame-system = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-staking = { git="https://github.com/cheme/substrate", branch="validation_io" }
frame-support = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-session = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-balances = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-authorship = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-staking = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-runtime = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-io = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-std = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-inherents = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-api = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-sudo = { git="https://github.com/cheme/substrate", branch="validation_io" }
frame-system-rpc-runtime-api = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-staking-reward-curve = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-offences = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-nicks = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-membership = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-indices = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-im-online = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-identity = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-grandpa = { git="https://github.com/cheme/substrate", branch="validation_io" }
frame-executive = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-elections-phragmen = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-democracy = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-collective = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-transaction-payment-rpc = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-transaction-payment-rpc-runtime-api = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-transaction-payment = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-authority-discovery = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-transaction-pool = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-version = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-session = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-offchain = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-consensus-babe = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-recovery = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-society = { git="https://github.com/cheme/substrate", branch="validation_io" }
fork-tree = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-utility = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-network = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-cli = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-client-db = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-executor = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-service = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-keystore = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-authority-discovery = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-block-builder = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-blockchain = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-network-gossip = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-state-machine = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-externalities = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-runtime-interface = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-application-crypto = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-serializer = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-rpc = { git="https://github.com/cheme/substrate", branch="validation_io" }
substrate-frame-rpc-system = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-authority-discovery = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-chain-spec = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-finality-grandpa = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-telemetry = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-transaction-pool = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-timestamp = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-block-builder = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-finality-grandpa = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-tracing = { git="https://github.com/cheme/substrate", branch="validation_io" }
substrate-prometheus-endpoint = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-keystore = { git="https://github.com/cheme/substrate", branch="validation_io" }
frame-benchmarking = { git="https://github.com/cheme/substrate", branch="validation_io" }
frame-benchmarking-cli = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-bounties = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-multisig = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-scheduler = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-tips = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-proxy = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-vesting = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-basic-authorship = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-consensus = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-consensus = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-consensus-babe = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-consensus-babe-rpc = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-consensus-epochs = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-consensus-slots = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-consensus-vrf = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-consensus-aura = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-wasm-interface = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-finality-grandpa-rpc = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-light = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-sync-state-rpc = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-arithmetic = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-storage = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-tracing = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-test-primitives = { git="https://github.com/cheme/substrate", branch="validation_io" }
substrate-build-script-utils = { git="https://github.com/cheme/substrate", branch="validation_io" }
substrate-test-client = { git="https://github.com/cheme/substrate", branch="validation_io" }
substrate-test-runtime = { git="https://github.com/cheme/substrate", branch="validation_io" }
substrate-test-runtime-client = { git="https://github.com/cheme/substrate", branch="validation_io" }
substrate-test-utils = { git="https://github.com/cheme/substrate", branch="validation_io" }
substrate-wasm-builder = { git="https://github.com/cheme/substrate", branch="validation_io" }
frame-election-provider-support = { git="https://github.com/cheme/substrate", branch="validation_io" }
frame-try-runtime = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-election-provider-multi-phase = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-mmr = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-mmr-primitives = { git="https://github.com/cheme/substrate", branch="validation_io" }
pallet-mmr-rpc = { git="https://github.com/cheme/substrate", branch="validation_io" }
remote-externalities = { git="https://github.com/cheme/substrate", branch="validation_io" }
sc-finality-grandpa-warp-sync = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-consensus-slots = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-npos-elections = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-npos-elections-compact = { git="https://github.com/cheme/substrate", branch="validation_io" }
sp-utils = { git="https://github.com/cheme/substrate", branch="validation_io" }
try-runtime-cli = { git="https://github.com/cheme/substrate", branch="validation_io" }
