[workspace]
members = [
	"consensus",
	"message-broker",
	"network",
	"parachain-upgrade",
	"primitives",
	"runtime",
	"test/runtime",
	"test/client",
	"test/parachain/runtime",
	"test/parachain/",
	"upward-message",
]

[profile.release]
panic = 'unwind'

[patch.crates-io]
memory-db = { git = "https://github.com/paritytech/trie", branch = "bkchr-debugging" }
hash-db = { git = "https://github.com/paritytech/trie", branch = "bkchr-debugging" }
