[workspace]
members = [
	"consensus",
	"message-broker",
	"network",
	"parachain-upgrade",
	"primitives",
	"rococo-parachains/",
	"rococo-parachains/pallets/parachain-info",
	"rococo-parachains/primitives",
	"rococo-parachains/runtime",
	"runtime",
	"service",
	"test/runtime",
	"test/client",
	"test/service",
	"test/relay-sproof-builder",
	"xcm-handler",
]

[profile.release]
panic = 'unwind'

[patch.crates-io]
trie-db = { git = 'https://github.com/cheme/trie', branch = 'skip_compact_values' }
hash-db = { git = 'https://github.com/cheme/trie', branch = 'skip_compact_values' }
