[package]
name = "cumulus-client-consensus-common"
description = "Cumulus specific common consensus implementations"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
# Substrate deps
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "bkchr-inherent-something-future" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "bkchr-inherent-something-future" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "bkchr-inherent-something-future" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "bkchr-inherent-something-future" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "bkchr-inherent-something-future" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "bkchr-inherent-something-future" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "bkchr-inherent-something-future" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "bkchr-inherent-something-future" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "bkchr-inherent-something-future" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "bkchr-inherent-something-future" }

# Polkadot deps
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "bkchr-inherent-something-future" }
polkadot-runtime = { git = "https://github.com/paritytech/polkadot", branch = "bkchr-inherent-something-future" }

# Other deps
futures = { version = "0.3.8", features = ["compat"] }
tokio = "0.1.22"
codec = { package = "parity-scale-codec", version = "2.0.0", features = [ "derive" ] }
tracing = "0.1.22"
async-trait = "0.1.42"
dyn-clone = "1.0.4"

[dev-dependencies]
# Substrate deps
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "bkchr-inherent-something-future" }

# Cumulus dependencies
cumulus-test-runtime = { path = "../../../test/runtime" }
cumulus-test-client = { path = "../../../test/client" }

# Other deps
futures-timer = "3.0.2"
