[package]
name = "cumulus-primitives-parachain-inherent"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
# Substrate dependencies
sp-inherents = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "cecton-integration-test-runtime-upgrade" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "cecton-integration-test-runtime-upgrade" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "cecton-integration-test-runtime-upgrade", optional = true }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "cecton-integration-test-runtime-upgrade", optional = true }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "cecton-integration-test-runtime-upgrade" }
sp-state-machine = { git = "https://github.com/paritytech/substrate", branch = "cecton-integration-test-runtime-upgrade", optional = true }
sp-trie = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "cecton-integration-test-runtime-upgrade" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "cecton-integration-test-runtime-upgrade", optional = true }

# Cumulus dependencies
cumulus-primitives-core = { path = "../core", default-features = false }

# Other dependencies
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = [ "derive" ] }
tracing = { version = "0.1.22", optional = true }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"cumulus-primitives-core/std",
	"sp-inherents/std",
	"sp-core/std",
	"sp-trie/std",
	"sp-std/std",
	"sp-state-machine",
	"tracing",
	"sp-runtime",
	"sc-client-api",
	"sp-api",
]
